### ISSUE TITLE
Add scripts to the path

### ISSUE THREAD

**Issue by fntlnz** [leodido/dockerfiles#4]
https://github.com/leodido/dockerfiles/blob/master/sphinxsearch:2.2.7/Dockerfile#L52-L55

I suggest to add `indexall.sh` and `searchd.sh` to `$PATH` .

Right now, to index for example I have to

```
docker run --rm leodido/sphinxsearch /indexall.sh
```

IMO this would be better,
```
docker run --rm leodido/sphinxsearch indexall.sh
```

**Comment by leodido** [comment]
:+1:
